;;; custom.el --- Emacs Configuration through Custom
;;; Commentary:
;;; Code:
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(all-the-icons-scale-factor 1.0)
 '(beacon-blink-delay 0.3)
 '(beacon-blink-duration 0.8)
 '(beacon-blink-when-focused t)
 '(beacon-blink-when-window-scrolls nil)
 '(beacon-color 0.4)
 '(beacon-mode t)
 '(beacon-push-mark nil)
 '(beacon-size 40)
 '(blink-cursor-mode nil)
 '(column-enforce-column 79)
 '(company-cmake-executable nil)
 '(company-global-modes '(not eshell-mode))
 '(company-idle-delay t)
 '(css-fontify-colors nil)
 '(css-indent-offset 2)
 '(cursor-type 'box)
 '(dired-sidebar-width 35)
 '(dired-use-ls-dired nil)
 '(display-time-24hr-format t)
 '(display-time-day-and-date t)
 '(display-time-interval 1)
 '(display-time-mode t)
 '(flx-ido-mode t)
 '(fringe-mode '(nil . 1) nil (fringe))
 '(global-company-mode t)
 '(ido-enable-flex-matching t)
 '(ido-everywhere t)
 '(ido-mode 'both nil (ido))
 '(ido-vertical-define-keys 'C-n-and-C-p-only)
 '(ido-vertical-mode t)
 '(isearch-lazy-highlight t)
 '(jdee-compiler '("javac"))
 '(jdee-server-dir "~/myJars")
 '(js-indent-level 2 t)
 '(js2-strict-missing-semi-warning nil)
 '(lazy-highlight-initial-delay 0)
 '(mc/always-repeat-command t)
 '(mc/always-run-for-all t)
 '(moody-mode-line-height 21)
 '(neo-autorefresh t)
 '(neo-window-position 'right)
 '(neo-window-width 30)
 '(olivetti-body-width 80)
 '(org-agenda-files
   '("~/todo.org" "~/Notes-in-Org-LaTeX/GNU-Emacs/gnu-emacs.org" "~/Notes-in-Org-LaTeX/Docker/docker.org"))
 '(org-format-latex-options
   '(:foreground default :background default :scale 2.0 :html-foreground "Black" :html-background "Transparent" :html-scale 1.0 :matchers
                 ("begin" "$1" "$" "$$" "\\(" "\\[")))
 '(org-highlight-latex-and-related '(latex))
 '(org-latex-classes
   '(("article" "\\documentclass[12pt, a4paper]{article}"
      ("\\section{%s}" . "\\section*{%s}")
      ("\\subsection{%s}" . "\\subsection*{%s}")
      ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
      ("\\paragraph{%s}" . "\\paragraph*{%s}")
      ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
 '(org-latex-listings 'minted)
 '(org-latex-pdf-process
   '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
 '(org-todo-keywords '((sequence "TODO" "DOING" "DONE")))
 '(package-selected-packages
   '(expand-region switch-window beacon writeroom-mode eshell-git-prompt vscode-icon dired-sidebar tide all-the-icons minions moody edit-server flx-ido vimrc-mode lorem-ipsum dockerfile-mode evil-org rainbow-mode smex esh-autosuggest evil-magit ido-vertical-mode markdown-mode whitespace-cleanup-mode magit spacemacs-theme highlight-escape-sequences dired-icon highlight-operators highlight-numbers company-jedi emmet-mode column-enforce-mode yasnippet-snippets yasnippet-classic-snippets which-key smooth-scrolling rainbow-delimiters prettier-js org-bullets nlinum-relative neotree js2-mode jedi java-snippets evil-surround evil-smartparens evil-commentary elpy dashboard base16-theme avy auto-indent-mode))
 '(python-indent-guess-indent-offset nil)
 '(shr-max-image-proportion 0.5)
 '(writeroom-global-effects
   '(writeroom-set-fullscreen writeroom-set-alpha writeroom-set-menu-bar-lines writeroom-set-tool-bar-lines writeroom-set-bottom-divider-width))
 '(writeroom-mode-line t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 150 :width normal :foundry "nil" :family "Monaco"))))
 '(avy-lead-face ((t (:foreground "#FF4E4e"))))
 '(avy-lead-face-0 ((t (:foreground "DarkGoldenrod2"))))
 '(bold ((t (:weight normal :foreground "DarkGoldenrod2"))))
 '(column-enforce-face ((t (:foreground "#ff4e4e" :underline t))))
 '(company-scrollbar-bg ((t (:background "#000000"))))
 '(company-scrollbar-fg ((t (:background "#aaaaaa"))))
 '(company-template-field ((t (:background "#333333" :foreground "#bbbbbb"))))
 '(company-tooltip ((t (:background "#333333" :foreground "#bbbbbb"))))
 '(company-tooltip-selection ((t (:background "#666666"))))
 '(dashboard-banner-logo-title-face ((t (:inherit default :overline t :foreground "#cbebff" :height 1.15 :family "Dejavu sans mono"))))
 '(dashboard-heading-face ((t (:inherit default :foreground "#CBEBFF" :height 1.1))))
 '(eshell-git-prompt-powerline-clean-face ((t (:background "MediumSeaGreen" :foreground "#000000"))))
 '(eshell-git-prompt-powerline-dir-face ((t (:background "#839DB2" :foreground "#000000"))))
 '(eshell-git-prompt-powerline-not-clean-face ((t (:background "DarkGoldenrod2" :foreground "#000000"))))
 '(fringe ((t (:background "#002b36"))))
 '(js2-function-param ((t (:foreground "#659F93"))))
 '(linum ((t (:background "#002b36" :foreground "#647C83"))))
 '(mc/cursor-face ((t (:background "#888888" :foreground "black"))))
 '(neo-dir-link-face ((t (:foreground "#fffafa" :height 140 :family "San Francisco"))))
 '(neo-file-link-face ((t (:height 140 :family "San Francisco"))))
 '(nlinum-relative-current-face ((t (:inherit linum :background "#002b36" :foreground "#c6c6c6" :weight normal))))
 '(org-block ((t (:background "#20282F" :foreground "#839DB2"))))
 '(org-document-title ((t (:height 2.0 :family "Georgia"))))
 '(org-level-1 ((t (:inherit outline-1 :weight bold :height 1.3))))
 '(org-level-2 ((t (:inherit outline-2 :weight bold :height 1.1))))
 '(org-level-3 ((t (:inherit outline-3 :weight bold :height 1.1))))
 '(org-table ((t (:background "#152432"))))
 '(variable-pitch ((t (:foreground "#eeeeee" :height 1.3 :family "CMU Serif")))))
